### ISSUE TITLE
error when trying to add admin 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/owncloud_deployer#57]
```
JS-NG> i = j.core.identity.me                                                                                                                                                                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    │      │                  └ 'i = j.core.identity.me'
    │      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7f3de30104c0>
    └ <code object <module> at 0x7f3de2e7f030, file "<stdin>", line 1>
  File "/usr/local/lib/python3.8/dist-packages/ptpython/repl.py", line 109, in compile_with_flags
    return compile(code, '<stdin>', mode,
File "<stdin>", line 1
    i = j.core.identity.me
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
          └ ConnectionRefusedError(111, 'Connection refused')
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
    │            └ ('167.172.36.61', 443)
    └ None
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
          │            │    │        └ 111
          │            │    └ <built-in function strerror>
          │            └ 111
          └ <class 'OSError'>
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
    │                   └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3de0c63790>
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
    └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
    │                  └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>
    └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno ...
          │             │      └ '/api/v1/users/9160'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3de0c63790>
          └ <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/9160 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 237, in me
    self.__class__._me = self.get(identity)
    │                    │        └ 'default'
    │                    └ IdentityFactory(Identity)
    └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 206, in get
    instance = self.find(name)
               │         └ 'default'
               └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 439, in find
    instance = super().find(name)
                            └ 'default'
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 129, in find
    instance = getattr(self, name, None)
                       │     └ 'default'
                       └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 492, in getter
    instance = self._get_object_from_config(name, factory.store.get(name))
               │                            │     │                 └ 'default'
               │                            │     └ IdentityFactory(Identity)
               │                            └ 'default'
               └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 404, in _get_object_from_config
    instance = self._create_instance(name, **data)
               │                     │       └ {'_tid': 9160, 'words': 'call angle armed tomorrow top opera seek short wolf ten unhappy bronze denial light system visual usele...
               │                     └ 'default'
               └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'_tid': 9160, 'words': 'call angle armed tomorrow top opera seek short wolf ten unhappy bronze denial light system visual usele...
               │          └ ()
               └ IdentityFactory(Identity)
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 83, in __init__
    self.verify_configuration()
    └ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 102, in verify_configuration
    resp = requests.get(f"{self.explorer_url}/users/{self._tid}")
           │               │                         └ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...
           │               └ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...
           └ <module 'requests' from '/usr/local/lib/python3.8/dist-packages/requests/__init__.py'>
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {}
           │              │           └ None
           │              └ 'https://explorer.testnet.grid.tf/api/v1/users/9160'
           └ <function request at 0x7f3de24df8b0>
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │                      │           │      └ {'params': None}
           │                      │           └ 'https://explorer.testnet.grid.tf/api/v1/users/9160'
           │                      └ 'get'
           └ <requests.sessions.Session object at 0x7f3de0cd2fd0>
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x7f3de0cd2fd0>
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
        │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │            └ <PreparedRequest [GET]>
        └ <requests.adapters.HTTPAdapter object at 0x7f3de0c63430>
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.ConnectionError'>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/9160 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    ?[36m│      │                  └ 'i = j.core.identity.me'?[m
    ?[36m│      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7f3de30104c0>?[m
    ?[36m└ <code object <module> at 0x7f3de2e7f030, file "<stdin>", line 1>?[m
  File "/usr/local/lib/python3.8/dist-packages/ptpython/repl.py", line 109, in compile_with_flags
    return compile(code, '<stdin>', mode,
File "<stdin>", line 1
    i = j.core.identity.me
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    ?[33;1mraise?[m err
    ?[36m      └ ConnectionRefusedError(111, 'Connection refused')?[m
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
    ?[36m│            └ ('167.172.36.61', 443)?[m
    ?[36m└ None?[m
  File "/usr/local/lib/python3.8/dist-packages/gevent/_socketcommon.py", line 607, in connect
    ?[33;1mraise?[m _SocketError(err, strerror(err))
    ?[36m      │            │    │        └ 111?[m
    ?[36m      │            │    └ <built-in function strerror>?[m
    ?[36m      │            └ 111?[m
    ?[36m      └ <class 'OSError'>?[m
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
    ?[36m│                   └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>?[m
    ?[36m└ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3de0c63790>?[m
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
    ?[36m└ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>?[m
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
    ?[36m│                  └ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>?[m
    ?[36m└ <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>?[m
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
    ?[33;1mraise?[m MaxRetryError(_pool, url, error or ResponseError(cause))
    ?[36m      │             │      │    │        │             └ 'unknown'?[m
    ?[36m      │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>?[m
    ?[36m      │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno ...?[m
    ?[36m      │             │      └ '/api/v1/users/9160'?[m
    ?[36m      │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3de0c63790>?[m
    ?[36m      └ <class 'urllib3.exceptions.MaxRetryError'>?[m
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/9160 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 237, in me
    self.__class__._me = self.get(identity)
    ?[36m│                    │        └ 'default'?[m
    ?[36m│                    └ IdentityFactory(Identity)?[m
    ?[36m└ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 206, in get
    instance = self.find(name)
    ?[36m           │         └ 'default'?[m
    ?[36m           └ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 439, in find
    instance = ?[35;1msuper?[m().find(name)
    ?[36m                        └ 'default'?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 129, in find
    instance = ?[35;1mgetattr?[m(self, name, None)
    ?[36m                   │     └ 'default'?[m
    ?[36m                   └ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 492, in getter
    instance = self._get_object_from_config(name, factory.store.get(name))
    ?[36m           │                            │     │                 └ 'default'?[m
    ?[36m           │                            │     └ IdentityFactory(Identity)?[m
    ?[36m           │                            └ 'default'?[m
    ?[36m           └ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 404, in _get_object_from_config
    instance = self._create_instance(name, **data)
    ?[36m           │                     │       └ {'_tid': 9160, 'words': 'call angle armed tomorrow top opera seek short wolf ten unhappy bronze denial light system visual usele...?[m
    ?[36m           │                     └ 'default'?[m
    ?[36m           └ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/base/factory.py", line 161, in _create_instance
    instance = self.type(*args, **kwargs)
    ?[36m           │          │       └ {'_tid': 9160, 'words': 'call angle armed tomorrow top opera seek short wolf ten unhappy bronze denial light system visual usele...?[m
    ?[36m           │          └ ()?[m
    ?[36m           └ IdentityFactory(Identity)?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 83, in __init__
    self.verify_configuration()
    ?[36m└ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...?[m
  File "/usr/local/lib/python3.8/dist-packages/jumpscale/core/identity/__init__.py", line 102, in verify_configuration
    resp = requests.get(f"{self.explorer_url}/users/{self._tid}")
    ?[36m       │               │                         └ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...?[m
    ?[36m       │               └ Identity(
  instance_name='default',
  _tid=9160,
  words='call angle armed tomorrow top opera seek short wolf ten unhappy bronz...?[m
    ?[36m       └ <module 'requests' from '/usr/local/lib/python3.8/dist-packages/requests/__init__.py'>?[m
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    ?[33;1mreturn?[m request('get', url, params=params, **kwargs)
    ?[36m       │              │           │         └ {}?[m
    ?[36m       │              │           └ None?[m
    ?[36m       │              └ 'https://explorer.testnet.grid.tf/api/v1/users/9160'?[m
    ?[36m       └ <function request at 0x7f3de24df8b0>?[m
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    ?[33;1mreturn?[m session.request(method=method, url=url, **kwargs)
    ?[36m       │                      │           │      └ {'params': None}?[m
    ?[36m       │                      │           └ 'https://explorer.testnet.grid.tf/api/v1/users/9160'?[m
    ?[36m       │                      └ 'get'?[m
    ?[36m       └ <requests.sessions.Session object at 0x7f3de0cd2fd0>?[m
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
    ?[36m       │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}?[m
    ?[36m       │         └ <PreparedRequest [GET]>?[m
    ?[36m       └ <requests.sessions.Session object at 0x7f3de0cd2fd0>?[m
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
    ?[36m    │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}?[m
    ?[36m    │            └ <PreparedRequest [GET]>?[m
    ?[36m    └ <requests.adapters.HTTPAdapter object at 0x7f3de0c63430>?[m
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    ?[33;1mraise?[m ?[35;1mConnectionError?[m(e, request=request)
    ?[36m      │                          └ <PreparedRequest [GET]>?[m
    ?[36m      └ <class 'requests.exceptions.ConnectionError'>?[m
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/9160 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused'))

HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/9160 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3de0c63d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
    
```

**Comment by sameh-farouk** [comment]
This is due to the removal of the **testnet** explorer.
Code updated to use **mainnet** identity to start threebot server, till js-sdk corrected to not depend on explorer identities.

A new docker image is available, `threefolddev/owncloud_deployer:edge`

**Comment by hossnys** [comment]
verified 
```
JS-NG> i = j.core.identity.me                             
JS-NG> i.admins                                                                                                                                                                                             
['samir1.3bot', 'sabrinasadik.3bot', 'linkmark.3bot', 'petep.3bot', 'mohamedamer.3bot', 'ahmedthabet.3bot', 'samehabouelsaad.3bot', 'bojlbawjpq.3bot']
```
