### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/owncloud_deployer#9]
I tried to build the Dockerfile using `--no-cache=true` option, on the build machine waleed.threefold.io since most of the layers were cached and I suspected some layers should but weren't updated. however, once the cache was invalidated, all subsequent docker build commands failed and I wasn't able to build a new image.

I tried to build it on another machine, and also to clear the poetry cache, but with no luck.

```
Sending build context to Docker daemon  20.99kB
Step 1/25 : FROM ubuntu:20.04
 ---> 825d55fb6340
Step 2/25 : LABEL maintainer="hammamw@incubaid.com"
 ---> Using cache
 ---> 57d8b050efa1
Step 3/25 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 3167e4dd445a
Step 4/25 : RUN apt-get update &&     apt-get upgrade -y
 ---> Using cache
 ---> 55117c3f453a
Step 5/25 : RUN apt-get install -y git curl wget                 python3-venv                 python3-pip                 redis-server                 tmux                 nginx                 build-essential     && pip3 install poetry
 ---> Using cache
 ---> b9c0c0c4c87e
Step 6/25 : RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - &&    apt-get install -y nodejs &&    npm install -g npm@latest &&     npm install --global yarn
 ---> Using cache
 ---> b8373c1416ab
Step 7/25 : RUN wget https://github.com/threefoldtech/zinit/releases/latest/download/zinit -O /sbin/zinit     && chmod +x /sbin/zinit
 ---> Using cache
 ---> c50c1eefdb04
Step 8/25 : RUN git clone https://github.com/threefoldtech/owncloud_deployer.git
 ---> Using cache
 ---> 2890de3461a8
Step 9/25 : RUN apt-get update && apt-get install -y gnupg software-properties-common curl &&    curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - &&    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" &&    apt-get update && apt-get install terraform
 ---> Using cache
 ---> 05c8485ee7a9
Step 10/25 : WORKDIR owncloud_deployer
 ---> Using cache
 ---> 75e077cad4d1
Step 11/25 : RUN cd jumpscale/packages/owncloud/frontend/ &&     yarn && yarn build
 ---> Using cache
 ---> 2c2fd6ae75e3
Step 12/25 : RUN chmod +x ./docker/init.sh
 ---> Using cache
 ---> 809766ba3078
Step 13/25 : RUN cd balance_server &&     yarn
 ---> Using cache
 ---> 89ab08489a1c
Step 14/25 : RUN poetry config virtualenvs.create false &&  poetry install --no-dev
 ---> Running in 162e04fc3342
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 105 installs, 12 updates, 0 removals

  • Updating six (1.14.0 /usr/lib/python3/dist-packages -> 1.16.0)
  • Updating certifi (2019.11.28 /usr/lib/python3/dist-packages -> 2019.11.28)
  • Updating charset-normalizer (2.0.12 -> 2.0.11)
  • Updating cryptography (36.0.2 -> 3.3.2)
  • Updating idna (2.8 /usr/lib/python3/dist-packages -> 3.3)
  • Updating urllib3 (1.25.8 /usr/lib/python3/dist-packages -> 1.26.8)
  • Installing frozenlist (1.3.0)
  • Installing multidict (6.0.2)
  • Installing pyopenssl (21.0.0)
  • Installing pytz (2021.3)
  • Updating requests (2.22.0 /usr/lib/python3/dist-packages -> 2.27.1)
  • Updating zipp (3.8.0 -> 3.7.0)
  • Installing aiosignal (1.2.0)
  • Installing async-timeout (4.0.2)
  • Installing attrs (21.4.0)
  • Installing bcrypt (3.2.0)
  • Updating importlib-metadata (4.11.3 -> 4.10.1)
  • Installing markupsafe (2.0.1)
  • Installing parso (0.7.1)
  • Installing josepy (1.12.0)
  • Installing pynacl (1.3.0)
  • Installing pyrfc3339 (1.1)
  • Installing smmap (5.0.0)
  • Installing wcwidth (0.2.5)
  • Installing yarl (1.7.2)
  • Installing zope.event (4.5.0)
  • Installing zope.hookable (5.1.0)
  • Installing zope.interface (5.4.0)
  • Installing acme (1.22.0)
  • Installing aiohttp (3.8.1)
  • Installing argh (0.26.2)
  • Installing configargparse (1.5.3)
  • Installing configobj (5.0.6)
  • Installing distro (1.6.0)
  • Installing docopt (0.6.2)
  • Installing future (0.18.2)
  • Installing gitdb (4.0.9)
  • Installing greenlet (1.0.0)
  • Installing invoke (1.6.0)
  • Installing jedi (0.17.2)
  • Installing mako (1.1.6)
  • Installing markdown (3.3.6)
  • Installing paramiko (2.9.2)
  • Installing parsedatetime (2.6)
  • Installing pathlib2 (2.3.6)
  • Installing pathtools (0.1.2)
  • Installing prompt-toolkit (2.0.10)
  • Installing pycryptodomex (3.14.1)
  • Installing pygments (2.11.2)
  • Installing python-dateutil (2.8.2)
  • Installing pyyaml (5.4.1)
  • Installing text-unidecode (1.3)
  • Installing urwid (2.1.2)
  • Installing websocket-client (1.2.3)
  • Installing wrapt (1.13.3)
  • Installing zope.component (5.0.1)
  • Installing aiohttp-sse-client (0.1.7)
  • Installing arrow (0.15.8)
  • Installing bottle (0.12.19)
  • Installing better-exceptions (0.2.3)
  • Installing certbot (1.22.0)
  • Installing click (7.1.2)
  • Installing crc16 (0.1.1)
  • Installing colorama (0.4.4)
  • Installing deprecated (1.2.13)
  • Installing dill (0.3.4)
  • Installing docker (4.2.2)
  • Installing fabric (2.6.0)
  • Installing faker (2.0.5)
  • Installing funcsigs (1.0.2)
  • Installing gevent (21.1.2)
  • Installing gitpython (3.1.26)
  • Installing jinja2 (2.11.3)
  • Installing jsonpickle (2.1.0)
  • Installing libtmux (0.8.5)
  • Installing loguru (0.3.2)
  • Installing mnemonic (0.19)
  • Updating msgpack (1.0.3 -> 0.6.2)
  • Installing pdoc3 (0.6.4)
  • Installing psutil (5.9.0)
  • Installing ptpython (2.0.6)
  • Installing pudb (2019.2)
  • Installing pyjwkest (1.4.2)
  • Installing pyjwt (1.7.1)
  • Installing pylzma (0.5.0)
  • Updating pyparsing (3.0.8 -> 3.0.7)
  • Installing python-http-client (3.3.5)
  • Installing pytoml (0.1.21)
  • Installing redis (3.5.3)
  • Installing secretconf (0.1.2)
  • Installing starkbank-ecdsa (2.0.3)
  • Installing stellar-base-sseclient (0.0.21)
  • Installing terminaltables (3.1.10)
  • Installing toml (0.10.2)
  • Installing watchdog (0.9.0)
  • Installing whoosh (2.7.4)

  EnvCommandError

  Command ['/usr/bin/python3', '-m', 'pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/89/9d/d6/bf5327e19830875afd6d311bdae9c6e037596a3cea16769178db43924a/pdoc3-0.6.4.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/89/9d/d6/bf5327e19830875afd6d311bdae9c6e037596a3cea16769178db43924a/pdoc3-0.6.4.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hh5s9pn_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hh5s9pn_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-hh5s9pn_/pip-egg-info
           cwd: /tmp/pip-req-build-hh5s9pn_/
      Complete output (43 lines):
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3023, in _dep_map
          return self.__dep_map
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2817, in __getattr__
          raise AttributeError(attr)
      AttributeError: _DistInfoDistribution__dep_map
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
          return self._pkg_info
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2817, in __getattr__
          raise AttributeError(attr)
      AttributeError: _pkg_info
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-req-build-hh5s9pn_/setup.py", line 15, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 138, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 795, in resolve
          new_requirements = dist.requires(req.extras)[::-1]
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2738, in requires
          dm = self._dep_map
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3025, in _dep_map
          self.__dep_map = self._compute_dependencies()
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3034, in _compute_dependencies
          for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3016, in _parsed_pkg_info
          metadata = self.get_metadata(self.PKG_INFO)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1421, in get_metadata
          value = self._get(path)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1617, in _get
          with open(path, 'rb') as stream:
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyparsing-3.0.8.dist-info/METADATA'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  

  at /usr/local/lib/python3.8/dist-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

The command '/bin/sh -c poetry config virtualenvs.create false &&  poetry install --no-dev' returned a non-zero code: 1
```

**Comment by sameh-farouk** [comment]
the end up being an old issue with poetry that seems happens with certain environments more than other and haven't get attention until recently, it was caused by a parallel pip install (Race condition between threads). no fix has been released yet, but there was a workaround for the affected systems by doing`poetry config experimental.new-installer false` or on recent poetry versions poetry config installer.max-workers=1.

build now is automated with a github action workflow where we also use the workaround mentioned above.

build passed now and was observed for some time with no problems.

**verified**
